<a href="https://colab.research.google.com/github/Binay1510/Python-training/blob/master/gw2022pdi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

let us learn machine learning


In [ ]:
a=10
b=20
c=a+b
c

30

Problems in ML:
1. Regression - prediction
2. Classifiaction - classify objs

observation
1. 700 ,800 ,1
2. 1200,1000,1
3. 150,100,2
4. 300,350,2


In [1]:
from sklearn import tree

#input
X = [[700, 800], [1200, 1000], [150, 100], [300, 350]]
#output
Y=  [1,2,2,2]

model=tree.DecisionTreeClassifier()
model.fit(X ,Y)

result=model.predict([[250,180]])
print(result)
print(type(result))

[2]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
np.__version__

'1.21.6'

In [3]:
numbers=[10,20,30,40,50]
print(numbers,type(numbers))

[10, 20, 30, 40, 50] <class 'list'>


In [4]:
array = np.array(numbers)
print(array, type(array))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [5]:
array = np.arange(10)
print(array)
print(array.shape)

image = [ [120, 22, 66], [22, 12, 88], [67, 12, 56] ]
array2d = np.array(image)
print(array2d)
print(array2d.shape)

# Explore Slicing on 1d and 2d array :)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[120  22  66]
 [ 22  12  88]
 [ 67  12  56]]
(3, 3)


In [6]:
numbers = [1, 1, 1, 1, 1, 1, 1, 1]
numbers = [0, 0, 0, 0, 0, 0, 0, 0]
print(numbers, len(numbers))

# array1 = np.ones(8)
# array1 = np.ones(8, dtype=np.int32)
array1 = np.zeros(8, dtype=np.int32)
print(array1)

print(array1.ndim)
print(array1.shape)

array2 = array1.reshape(2, 2, 2)
print(array2)
print(array2.ndim)
print(array2.shape)

array3 = array2.ravel()
print(array3)

[0, 0, 0, 0, 0, 0, 0, 0] 8
[0 0 0 0 0 0 0 0]
1
(8,)
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
3
(2, 2, 2)
[0 0 0 0 0 0 0 0]


In [7]:
chessboard = np.zeros((8, 8), dtype=np.int32)
print(chessboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [8]:
chessboard[1::2, 0::2] = 1
chessboard[0::2, 1::2] = 1
print(chessboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
import numpy as np


In [10]:
A=list(range(1,11))
print(A)
print(A[1:7:2])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6]


In [11]:
# B = np.arange(1, 11)
B = np.arange(1, 11)
print(B)
print(B.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [12]:
# Indexing
print(B[3])
print(B[6])

# Slicing
print(B[3:7])
print(B[:7])
print(B[3:])

4
7
[4 5 6 7]
[1 2 3 4 5 6 7]
[ 4  5  6  7  8  9 10]


In [13]:
# Step Slicing
print(B[1:7:2])

[2 4 6]


In [14]:
covid_data = np.array([
    # col1 -> confirmed cases
    # col2 -> recovered cases
    # row1 -> ludhiana
    # row2 -> jalandhar
    # row3 -> chandigarh
    [8, 9],
    [10, 20],
    [12, 14]
])
covid_data

array([[ 8,  9],
       [10, 20],
       [12, 14]])

In [15]:
result = covid_data - 3
print(result)


[[ 5  6]
 [ 7 17]
 [ 9 11]]


In [16]:
covid_data[0:2, 1]

array([ 9, 20])

In [17]:
print(covid_data.min())
print(covid_data.max())
print(covid_data.sum())


8
20
73


In [18]:
array = np.arange(10, 200, 10)
print(array)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190]


In [19]:
np.savetxt("numbers.txt", array, delimiter=" ")
print("File Saved")

File Saved
